ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TREE_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TIMELINE_EVENT_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TIMELINE_EVENT_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TIMELINE_EVENT_DELETE';
