ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACCESS_GRANT_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACCESS_GRANT_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACCESS_GRANT_DELETE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACCESS_CODE_REVOKE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACCESS_CODE_DELETE';
